collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true

# gem install jekyll-pagination
paginate: 3                 # 페이징 처리 개수
paginate_path: "/portfolio/page:num/"